/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ColumbusRecruitmentData {
  title: string;
  logo: Image;
  /**
   * @minItems 1
   */
  products: [Product, ...Product[]];
}
export interface Image {
  link: string;
  altText: string;
}
export interface Product {
  articleNumber: string;
  ean: string;
  link: string;
  image: Image;
  title: string;
  description: string;
  brandName: string;
  brandLogo: string;
  price: number;
  promotion?: Promotion | null;
}
export interface Promotion {
  name: string;
  percentage: number;
}
